### ISSUE TITLE
"whois.json(domain) function" not working 

### ISSUE THREAD

**Issue by sengineerhong** [MaxOrelus/whois-promise#1]
When I ran code (whois.json('mozilla.org').then(response => console.log(response));) 
return object is {},

src/utils/parse.js
I think, split arg need to be changed. May be.. 
if (isIP) {
    whoisArr = whois.split('\n').map(str => str.trim());
  } else if (isFQDN) {
    // whoisArr = whois.split('\r\n').map(str => str.trim());
      whoisArr = whois.split('\n').map(str => str.trim());
  } else {
    // we don't handle just hostname lookups
    return {};
  }

Thanks.

**Comment by MaxOrelus** [comment]
Hi, 

Could you let me know what version you are running?

**Comment by MaxOrelus** [comment]
Whois database ended up changing the raw output. Thanks for pointing this out. Changes are reflected in new version update.
